#ifndef MONITOR_MENU_ICON_BITMAPS_H
#define MONITOR_MENU_ICON_BITMAPS_H

#include <stdint.h>

#define MONITOR_MENU_ICON_BITMAP_WIDTH 32
#define MONITOR_MENU_ICON_BITMAP_HEIGHT 32

extern const uint8_t MONITOR_MENU_WIFI_ICON_BITMAP_32[128];
extern const uint8_t MONITOR_MENU_BT_ICON_BITMAP_32[128];

#endif /* MONITOR_MENU_ICON_BITMAPS_H */
